# ============================================
# BUN 1.3 OPTIMIZED CONFIGURATION
# Tarkov Casino - Root Workspace Configuration
# ============================================

# ====================
# INSTALL SETTINGS
# ====================
[install]
# Enable production optimizations in CI
production = false

# Faster installs with auto-install
auto = true

# Use exact versions (set to true for deterministic builds)
exact = false

# ====================
# INSTALL.CACHE
# ====================
[install.cache]
# Cache directory
dir = "~/.bun/install/cache"

# Enable cache for faster installs
disable = false

# Disable manifest cache to always get latest versions (set true for offline)
disableManifest = false

# ====================
# INSTALL.LOCKFILE
# ====================
[install.lockfile]
# Save lockfile
save = true

# ====================
# TEST CONFIGURATION
# ====================
[test]
# Root-level test setup
preload = ["./happydom.ts", "./test-setup.ts"]

# Enable code coverage by default
coverage = true

# Coverage threshold (percentage)
coverageThreshold = 75

# Test timeout (milliseconds)
timeout = 10000

# Don't bail on first failure (run all tests)
bail = false

# Test file patterns
testNamePattern = ["**/*.test.ts", "**/*.test.tsx"]

# ====================
# LOGGING
# ====================
# Set log level (debug, info, warn, error)
logLevel = "info"

