# ============================================
# BUN 1.3 OPTIMIZED CONFIGURATION
# Tarkov Casino - Root Workspace Configuration
# ============================================

# ====================
# INSTALL SETTINGS
# ====================
[install]
# Enable production optimizations in CI (set via env: BUN_ENV=production)
production = false

# Faster installs with auto-install
auto = true

# Use exact versions for deterministic builds
exact = true

# Optimize registry fetching
registry = "https://registry.npmjs.org/"

# ====================
# INSTALL.CACHE
# ====================
[install.cache]
# Cache directory
dir = "~/.bun/install/cache"

# Enable cache for faster installs
disable = false

# Enable manifest cache for faster subsequent installs
disableManifest = false

# Scope hoisting for smaller bundles and faster installs
scopeHoist = true

# ====================
# INSTALL.LOCKFILE
# ====================
[install.lockfile]
# Save lockfile
save = true

# ====================
# TEST CONFIGURATION
# ====================
[test]
# Root-level test setup
preload = ["./happydom.ts", "./test-setup.ts"]

# Enable code coverage by default
coverage = true

# Coverage threshold (percentage)
coverageThreshold = 75

# Test timeout (milliseconds)
timeout = 10000

# Don't bail on first failure (run all tests)
bail = false

# Test file patterns
testNamePattern = ["**/*.test.ts", "**/*.test.tsx"]

# ====================
# RUNTIME OPTIMIZATIONS
# ====================
[runtime]
# Use Bun's optimized JSC engine
useJIT = true

# Optimize startup time
preload = []

# ====================
# LOGGING
# ====================
# Set log level (debug, info, warn, error)
logLevel = "info"

[console]
depth = 5

# ====================
# FULLSTACK DEV SERVER
# ====================
[serve]
# Static file serving optimizations
[serve.static]
plugins = ["bun-plugin-tailwind"]

# Development settings
[serve.development]
# Enable hot module replacement
hmr = true

# Log browser console to terminal
console = true

# ====================
# BUILD OPTIMIZATIONS
# ====================
[build]
# Default target
target = "browser"

# Enable sourcemaps by default
sourcemap = "external"

# ====================
# PERFORMANCE TUNING
# ====================
[performance]
# Parallel processing (use all CPU cores)
parallel = true

# Memory limits (in MB, 0 = unlimited)
memoryLimit = 0