# Bun configuration for frontend testing

[test]
# Use test setup and Happy DOM
preload = ["./happy-dom.ts", "./src/test-utils/test-setup.ts"]

# Coverage settings
coverage = true

# Test timeout
timeout = 10000