import { beforeAll, afterEach, afterAll, vi } from 'vitest'

process.env.NODE_ENV = 'test'
process.env.APPWRITE_ENDPOINT = 'http://localhost:5000/v1'
process.env.APPWRITE_PROJECT_ID = 'test-project-id'
process.env.APPWRITE_API_KEY = 'test-api-key-at-least-32-characters-long-for-security-compliance-and-validation'
process.env.JWT_SECRET = 'test-jwt-secret-at-least-32-characters-long-for-security-compliance-and-validation-purposes-only'
process.env.STARTING_BALANCE = '10000'
process.env.DAILY_BONUS = '1000'
process.env.LOG_LEVEL = 'error'
process.env.ENABLE_REQUEST_LOGGING = 'false'
process.env.ENABLE_GAME_LOGGING = 'false'
process.env.ENABLE_SECURITY_LOGGING = 'false'
process.env.MAX_REQUEST_SIZE = '10mb'
process.env.REQUEST_TIMEOUT = '30000'
process.env.RATE_LIMIT_WINDOW = '900000'
process.env.RATE_LIMIT_MAX = '100'
process.env.HEALTH_CHECK_TIMEOUT = '5000'
process.env.METRICS_ENABLED = 'false'
process.env.REDIS_ENABLED = 'false'
